### ISSUE TITLE
TODO [3/3/22]

### ISSUE THREAD

**Issue by BradRyan** [BradRyan/dao-frontend#1]
- [ ] How do we load NFT's purchased for given connected wallet?
- [ ] Layout some basic pages (FAQ, pre mint countdown, mint page, post mint)
- [ ] Upon minting, show content for "What next"
